In [5]:
# concatenate arrays
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.concatenate((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
# concatenate the 2d arrays along vertical direction
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b),axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [2]:
# numpy has stack function to join along horizontal direction/vertical direction
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))
print(c)


[1 2 3 4 5 6]


In [5]:
# along vertical direction
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[1,2,3]])
c=np.vstack((a,b))
d=np.hstack((a,b))
print(c)
print('\n')
print(d)


[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


[[1 2 3 7 8 9]
 [4 5 6 1 2 3]]


In [6]:
# stacking along the depth
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.dstack((a,b))
print(c)


[[[1 4]
  [2 5]
  [3 6]]]
